"""Add is_active column to user table

Revision ID: 231ab15a7ec3
Revises: 9337e1a46e9d
Create Date: 2024-09-27 18:18:45.815712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231ab15a7ec3'
down_revision: Union[str, None] = '9337e1a46e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
